import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:tracend/app/environment.dart';
import 'package:tracend/app/theme/tracend_tokens.dart';
import 'package:tracend/features/account/account_screen.dart';
import 'package:tracend/features/account/notification_repository.dart';
import 'package:tracend/features/account/privacy_export_repository.dart';
import 'package:tracend/features/account/account_deletion_repository.dart';
import 'package:tracend/features/coach/coach_repository.dart';
import 'package:tracend/features/consent/ai_coaching_consent.dart';
import 'package:tracend/features/health/health_repository.dart';
import 'package:tracend/features/health/health_models.dart';
import 'package:tracend/features/nutrition/nutrition_repository.dart';
import 'package:tracend/features/train/workout_detail_screen.dart';
import 'package:tracend/features/train/workout_repository.dart';
import 'package:tracend/features/today/check_in_gate.dart';
import 'package:tracend/features/today/check_in_queue.dart';
import 'package:tracend/features/today/check_in_sheet.dart';
import 'package:tracend/features/today/daily_brief_repository.dart';
import 'package:tracend/features/today/widgets/fuel_rail_card.dart';
import 'package:tracend/features/today/widgets/plan_progress_line.dart';
import 'package:tracend/features/today/widgets/today_hero.dart';
import 'package:tracend/features/today/widgets/today_session_card.dart';
import 'package:tracend/features/today/widgets/today_tiles.dart';
import 'package:tracend/features/today/widgets/your_week_card.dart';
import 'package:tracend/shared/widgets/micro_motion.dart';
import 'package:tracend/shared/widgets/pressable.dart';
import 'package:tracend/shared/widgets/tracend_scaffold.dart';
import 'package:tracend/shared/widgets/tracend_skeleton.dart';
import 'package:tracend/shared/widgets/tracend_toast.dart';

/// Today's meal plan (null when it failed to load) and confirmed meals.
typedef TodayMeals = ({NutritionSchedule? schedule, List<MealEntry> meals});

class TodayScreen extends StatefulWidget {
  const TodayScreen({
    required this.environment,
    this.onSignOut,
    this.workouts,
    this.health = const ManualHealthRepository(),
    this.coach = const FixtureCoachRepository(),
    this.brief = const FixtureDailyBriefRepository(),
    this.nutrition = const FixtureNutritionRepository(),
    this.queueFactory,
    this.checkInSender,
    this.onOpenNutrition,
    this.onOpenTrain,
    this.aiConsent,
    this.checkInGate,
    super.key,
  });

  final AppEnvironment environment;
  final Future<void> Function()? onSignOut;
  final WorkoutRepository? workouts;
  final HealthRepository health;
  final CoachRepository coach;
  final DailyBriefRepository brief;
  final NutritionRepository nutrition;

  /// Builds the pending-check-in replay queue. Defaults to the real
  /// SharedPreferences-backed queue; tests inject a fake.
  final CheckInQueue? Function()? queueFactory;

  /// Performs the `save_daily_check_in` RPC during replay. Defaults to the
  /// real Supabase client; tests inject a recording fake.
  final CheckInSend? checkInSender;

  /// Shell wiring: switch to the Nutrition tab ("Log a meal").
  final VoidCallback? onOpenNutrition;

  /// Shell wiring: switch to the Train tab. "Open in Train" on today's
  /// session opens Train when this is wired and the workout itself
  /// otherwise.
  final VoidCallback? onOpenTrain;

  /// The daily decision is generated by the AI provider only while this is
  /// granted. Null without a backend, where nothing is sent.
  final AiCoachingConsentController? aiConsent;

  /// The shell's morning check-in gate. Today sets it while today's
  /// check-in is missing; without it, the hero offers a "Check in" chip.
  final CheckInGate? checkInGate;

  @override
  State<TodayScreen> createState() => _TodayScreenState();
}

class _TodayScreenState extends State<TodayScreen> {
  late Future<HealthHistory> _healthHistory;
  late Future<DailyBrief> _brief;
  late Future<NutritionTargets?> _targets;
  late Future<TodayMeals> _meals;
  late Future<CoachDecision?> _latestDecision;
  bool _syncing = false;

  /// Today's check-in as this phone knows it: saved (also when only queued
  /// offline) or put off with "Not today". Each holds the day it was set.
  String? _checkedInOn;
  String? _skippedOn;
  DailyBrief? _lastBrief;
  static const _checkedInKey = 'today_check_in_saved_on';
  static const _skippedKey = 'today_check_in_skipped_on';

  /// What the last sync could not refresh, shown on the hero until a sync
  /// succeeds.
  String? _syncIssue;

  /// Auto health sync runs at most once per 30 minutes and never triggers a
  /// permission prompt: it fires only when a previous sync already succeeded.
  static const _autoSyncInterval = Duration(minutes: 30);

  bool get _aiAllowed => widget.aiConsent?.granted ?? true;

  /// Granting AI coaching brings today's decision without waiting for a sync.
  void _consentChanged() {
    setState(() {});
    if (_aiAllowed) _refreshDecisionAfterEvidence();
  }

  @override
  void didUpdateWidget(TodayScreen oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.aiConsent != widget.aiConsent) {
      oldWidget.aiConsent?.removeListener(_consentChanged);
      widget.aiConsent?.addListener(_consentChanged);
    }
  }

  @override
  void dispose() {
    widget.aiConsent?.removeListener(_consentChanged);
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    widget.aiConsent?.addListener(_consentChanged);
    _reloadHealth();
    _targets = widget.nutrition.loadTargets();
    _meals = _loadMeals();
    _brief = _loadBrief();
    _latestDecision = widget.coach.loadLatest();
    _restoreCheckInDays();
    _autoSyncHealthIfNeeded();
    _replayPendingCheckIn();
  }

  /// Deliver any check-in queued while offline: the sheet persists the
  /// envelope before its RPC, and this replays it with the same idempotency
  /// key (the server deduplicates). The stored answer day's date is sent as
  /// recorded — a check-in belongs to the day it was answered, never
  /// re-dated to today. Silent by design: on failure the envelope stays
  /// stored and the next launch retries; on success the brief reloads
  /// because the check-in now colors today's coaching context.
  Future<void> _replayPendingCheckIn() async {
    if (!widget.environment.hasSupabaseConfiguration) return;
    try {
      final queue = await _resolveQueue();
      if (queue == null) return;
      final outcome = await queue.replay(_replaySender);
      if (outcome == CheckInReplayOutcome.delivered && mounted) {
        setState(() {
          _brief = _loadBrief();
        });
        // The replayed check-in is new evidence: today's decision may have
        // been generated without it and must be refreshed.
        await _refreshDecisionAfterEvidence();
      }
    } on Exception {
      // Keep the envelope; retried on next launch.
    }
  }

  Future<bool> _replaySender(
    String localDate,
    String timezone,
    String idempotencyKey,
    Map<String, dynamic> payload,
  ) async {
    if (widget.checkInSender != null) {
      return widget.checkInSender!(
        localDate,
        timezone,
        idempotencyKey,
        payload,
      );
    }
    await Supabase.instance.client.rpc(
      'save_daily_check_in',
      params: {
        'local_date': localDate,
        'timezone': timezone,
        'idempotency_key': idempotencyKey,
        'payload': payload,
      },
    );
    return true;
  }

  Future<CheckInQueue?> _resolveQueue() async {
    if (widget.queueFactory != null) return widget.queueFactory!();
    final preferences = await SharedPreferences.getInstance();
    return CheckInQueue(
      preferences,
      userId: Supabase.instance.client.auth.currentUser?.id,
    );
  }

  /// Today's meal plan and confirmed meals for the fuel rail. A failure
  /// leaves the schedule null so the card says the plan did not load.
  Future<TodayMeals> _loadMeals() async {
    final nutrition = widget.nutrition;
    final now = DateTime.now();
    try {
      final meals = await nutrition.loadMeals(now);
      final schedule = nutrition is NutritionScheduleRepository
          ? await (nutrition as NutritionScheduleRepository).loadSchedule(now)
          : const NutritionSchedule(title: '', items: []);
      return (schedule: schedule, meals: meals);
    } catch (error) {
      debugPrint('Today: meals failed: $error');
      return (schedule: null, meals: const <MealEntry>[]);
    }
  }

  /// Loads the brief and, once it arrives, sets the check-in gate from it.
  Future<DailyBrief> _loadBrief() {
    final future = widget.brief.load(DateTime.now());
    future.then((brief) {
      if (!mounted) return;
      _lastBrief = brief;
      _updateGate();
    }, onError: (_) {});
    return future;
  }

  bool _checkedIn(DailyBrief brief) =>
      brief.checkIn != null || _checkedInOn == brief.localDate;

  void _updateGate() {
    final brief = _lastBrief;
    widget.checkInGate?.update(
      required:
          brief != null && !_checkedIn(brief) && _skippedOn != brief.localDate,
      onCheckIn: _openCheckIn,
      onSkip: _skipCheckIn,
    );
  }

  Future<void> _restoreCheckInDays() async {
    try {
      final preferences = await SharedPreferences.getInstance();
      if (!mounted) return;
      setState(() {
        _checkedInOn = preferences.getString(_checkedInKey);
        _skippedOn = preferences.getString(_skippedKey);
      });
      _updateGate();
    } catch (_) {
      // Without stored days the gate follows the brief alone.
    }
  }

  Future<void> _rememberDay(String key, String day) async {
    try {
      final preferences = await SharedPreferences.getInstance();
      await preferences.setString(key, day);
    } catch (_) {
      // The gate still opens for this session.
    }
  }

  /// "Not today": the tab bar comes back until tomorrow.
  void _skipCheckIn() {
    final day = _lastBrief?.localDate ?? _dateKey(DateTime.now());
    setState(() => _skippedOn = day);
    _updateGate();
    _rememberDay(_skippedKey, day);
  }

  void _reloadHealth() {
    _healthHistory = widget.health.loadHistory();
  }

  void _reloadBriefAndHealth() {
    _reloadHealth();
    setState(() {
      _brief = _loadBrief();
      _targets = widget.nutrition.loadTargets();
      _meals = _loadMeals();
    });
  }

  Future<void> _autoSyncHealthIfNeeded() async {
    if (!widget.environment.hasSupabaseConfiguration) return;
    try {
      final status = await widget.health.loadStatus();
      final last = status.lastSuccessfulSync;
      if (last == null) return; // never connected -> manual via profile only
      if (DateTime.now().difference(last) < _autoSyncInterval) return;
      await widget.health.sync();
      if (mounted) _reloadBriefAndHealth();
    } catch (_) {
      // Silent: the hero sync button stays available for an explicit retry.
    }
  }

  /// Sync everything: Apple Health (when connected), the daily brief, and
  /// today's coaching decision. Each stage fails independently and the result
  /// message reports exactly what could not be refreshed — a HealthKit read
  /// that returns `unavailable` counts as a failure, and a never-connected
  /// Apple Health is reported as skipped, never as "up to date".
  Future<void> _syncEverything() async {
    if (_syncing) return;
    setState(() => _syncing = true);
    final failures = <String>[];
    var healthSkipped = false;
    try {
      try {
        final status = await widget.health.loadStatus();
        if (status.lastSuccessfulSync != null) {
          final synced = await widget.health.sync();
          if (synced.state == HealthConnectionState.unavailable) {
            failures.add('Apple Health');
          }
        } else {
          healthSkipped = true;
        }
      } catch (_) {
        failures.add('Apple Health');
      }
      if (!mounted) return;
      _reloadBriefAndHealth();
      if (widget.environment.hasSupabaseConfiguration) {
        try {
          final latest = await widget.coach.loadLatest();
          final today = _dateKey(DateTime.now());
          final citedCheckInMissing =
              latest != null &&
              latest.localDate == today &&
              latest.missingData.contains('recovery_check_in');
          if (_aiAllowed &&
              (latest == null ||
                  latest.localDate != today ||
                  citedCheckInMissing)) {
            // Same freshness rule as _refreshDecisionAfterEvidence: a
            // decision generated before the check-in landed is stale.
            await widget.coach.generate();
          }
          if (!mounted) return;
          setState(() {
            _latestDecision = widget.coach.loadLatest();
          });
        } catch (_) {
          failures.add('coach decision');
        }
      }
      if (!mounted) return;
      final String message;
      if (failures.isNotEmpty) {
        message = 'Synced, but unavailable: ${failures.join(', ')}.';
      } else if (healthSkipped) {
        message =
            'Synced. Apple Health is not connected — set it up in your profile.';
      } else {
        message = 'Everything is up to date.';
      }
      setState(() {
        _syncIssue = failures.isEmpty
            ? null
            : 'Could not refresh ${failures.join(' or ')}. Pull down or tap '
                  'Sync to try again.';
      });
      TracendToast.show(
        context,
        message,
        icon: failures.isEmpty
            ? CupertinoIcons.checkmark_alt
            : CupertinoIcons.exclamationmark_triangle,
      );
    } finally {
      if (mounted) setState(() => _syncing = false);
    }
  }

  String _dateKey(DateTime value) =>
      '${value.year.toString().padLeft(4, '0')}-'
      '${value.month.toString().padLeft(2, '0')}-'
      '${value.day.toString().padLeft(2, '0')}';

  /// Refreshes the coaching decision after new evidence arrived.
  ///
  /// The daily decision generates once per day, but it can be generated
  /// before the morning check-in — in that state the policy permits only
  /// gather-data actions and cites `recovery_check_in` as missing, and the
  /// card would keep saying "gather data" all day even after the check-in
  /// lands (the bar reads the live table, so the two contradicted each
  /// other). When today's decision cited the check-in as missing, a new
  /// decision is generated (new idempotency key → new audited row); the
  /// guardrails are unchanged, only the evidence is fresh. Failures are
  /// silent — the stale decision remains valid coaching.
  Future<void> _refreshDecisionAfterEvidence() async {
    if (!widget.environment.hasSupabaseConfiguration || !_aiAllowed) return;
    try {
      final latest = await widget.coach.loadLatest();
      final today = _dateKey(DateTime.now());
      final citedCheckInMissing =
          latest != null &&
          latest.localDate == today &&
          latest.missingData.contains('recovery_check_in');
      // Checked again after the load: Today stays mounted while AI coaching
      // is turned off in Account, so the answer can change during the wait.
      if (_aiAllowed &&
          (latest == null ||
              latest.localDate != today ||
              citedCheckInMissing)) {
        await widget.coach.generate();
      }
      if (!mounted) return;
      setState(() {
        _latestDecision = widget.coach.loadLatest();
      });
    } catch (_) {
      // Stale-but-valid decision stays on screen; the hero sync retries.
    }
  }

  Future<void> _openCheckIn() async {
    final saved = await showCheckInSheet(
      context,
      widget.environment,
      sender: widget.checkInSender,
    );
    if (saved && mounted) {
      final day = _lastBrief?.localDate ?? _dateKey(DateTime.now());
      setState(() => _checkedInOn = day);
      _updateGate();
      await _rememberDay(_checkedInKey, day);
    }
    if (mounted) {
      setState(() {
        _brief = _loadBrief();
      });
      await _refreshDecisionAfterEvidence();
    }
  }

  /// Opens the brief's workout: the one planned for the date the brief was
  /// loaded for. A fixture brief carries no workout id, so its repository's
  /// workout opens instead.
  Future<void> _openWorkout(DailyBrief brief) async {
    final row = brief.workout;
    PlannedWorkout? workout;
    if (row != null && row['id'] is String) {
      workout = PlannedWorkout.fromHubJson(row);
    } else {
      try {
        workout = await widget.workouts?.loadTodayWorkout();
      } catch (e) {
        debugPrint('Non-critical error: $e');
      }
    }
    if (workout == null || !mounted) return;
    final completed = await Navigator.of(context).push<bool>(
      CupertinoPageRoute(
        builder: (_) => WorkoutDetailScreen(
          repository: widget.workouts,
          workout: workout,
          sessionDate: DateTime.tryParse(brief.localDate) ?? DateTime.now(),
        ),
      ),
    );
    if (completed == true && mounted) {
      setState(() => _brief = _loadBrief());
    }
  }

  void _openAccount() => Navigator.of(context).push<void>(
    CupertinoPageRoute(
      builder: (_) => AccountScreen(
        environment: widget.environment,
        onSignOut: widget.onSignOut,
        health: widget.health,
        coach: widget.coach,
        notifications: widget.environment.hasSupabaseConfiguration
            ? SupabaseNotificationRepository(Supabase.instance.client)
            : const FixtureNotificationRepository(),
        exports: widget.environment.hasSupabaseConfiguration
            ? SupabasePrivacyExportRepository(Supabase.instance.client)
            : const FixturePrivacyExportRepository(),
        deletion: widget.environment.hasSupabaseConfiguration
            ? SupabaseAccountDeletionRepository(Supabase.instance.client)
            : const FixtureAccountDeletionRepository(),
        aiConsent: widget.aiConsent,
      ),
    ),
  );

  @override
  Widget build(BuildContext context) {
    final now = DateTime.now();
    // "Good afternoon" cannot fit a 320pt screen at the largest text sizes
    // without breaking a word, so there the title is "Today" and the
    // greeting moves into the subtitle.
    final compactTitle = MediaQuery.textScalerOf(context).scale(34) > 48;
    // Today's pressable rows and cards ink on this, so the screen also works
    // when it is mounted without a Scaffold.
    return Material(
      type: MaterialType.transparency,
      child: TracendScrollView(
        title: compactTitle ? 'Today' : _greeting(now),
        subtitle: compactTitle
            ? '${_greeting(now)}, ${_formattedDate(now)}'
            : _formattedDate(now),
        onRefresh: _syncEverything,
        trailing: _AccountButton(onPressed: _openAccount),
        children: [
          FutureBuilder<DailyBrief>(
            future: _brief,
            builder: (context, snapshot) {
              // FutureBuilder retains the previous data when the future is
              // swapped (check-in / health sync reloads). Prefer it over the
              // waiting state so _BriefContent stays mounted: stagger
              // entrances don't replay and score count-ups animate on change.
              final brief = snapshot.data;
              if (brief != null) {
                return _BriefContent(
                  brief: brief,
                  targets: _targets,
                  meals: _meals,
                  latestDecision: _latestDecision,
                  aiAllowed: _aiAllowed,
                  healthHistory: _healthHistory,
                  syncing: _syncing,
                  syncIssue: _syncIssue,
                  onSync: _syncEverything,
                  onOpenNutrition: widget.onOpenNutrition,
                  onOpenWorkout:
                      widget.onOpenTrain ?? () => _openWorkout(brief),
                  onCheckIn: _openCheckIn,
                  checkedIn: _checkedIn(brief),
                  offerCheckIn:
                      widget.checkInGate == null ||
                      _skippedOn == brief.localDate,
                );
              }
              if (snapshot.connectionState == ConnectionState.waiting) {
                return const _BriefSkeleton();
              }
              return TracendCard(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Use your approved plan.',
                      style: Theme.of(context).textTheme.headlineSmall,
                    ),
                    const SizedBox(height: TracendSpacing.xs),
                    const Text(
                      'The daily brief is unavailable. Workout and meal logging '
                      'remain available. Pull down to try again.',
                    ),
                  ],
                ),
              );
            },
          ),
        ],
      ),
    );
  }

  /// A plain greeting by the time of day; no name is invented.
  String _greeting(DateTime now) {
    if (now.hour >= 5 && now.hour < 12) return 'Good morning';
    if (now.hour >= 12 && now.hour < 18) return 'Good afternoon';
    return 'Good evening';
  }

  String _formattedDate(DateTime value) {
    const weekdays = [
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
      'Sunday',
    ];
    const months = [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ];
    return '${weekdays[value.weekday - 1]} ${value.day} '
        '${months[value.month - 1]}';
  }
}

/// The account control in the large title: a round avatar in a 44pt
/// target, named "Open account" for VoiceOver and as its tooltip.
class _AccountButton extends StatelessWidget {
  const _AccountButton({required this.onPressed});

  final VoidCallback onPressed;

  @override
  Widget build(BuildContext context) {
    final colors = context.tracendColors;
    return Tooltip(
      message: 'Open account',
      excludeFromSemantics: true,
      child: Pressable(
        onTap: onPressed,
        semanticLabel: 'Open account',
        borderRadius: BorderRadius.circular(TracendRadii.pill),
        child: SizedBox.square(
          dimension: 44,
          child: Center(
            child: DecoratedBox(
              decoration: BoxDecoration(
                color: colors.surfaceRaised,
                shape: BoxShape.circle,
              ),
              child: SizedBox.square(
                dimension: 36,
                child: Icon(
                  CupertinoIcons.person_fill,
                  size: 19,
                  color: colors.textSecondary,
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

/// Today in the shape it is about to take: the hero, the check-in and
/// workout rows, and the trend. One label for VoiceOver.
class _BriefSkeleton extends StatelessWidget {
  const _BriefSkeleton();

  @override
  Widget build(BuildContext context) => Semantics(
    label: 'Loading Today',
    container: true,
    child: const Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        TracendSkeleton.block(height: 248),
        SizedBox(height: TracendSpacing.xs),
        TracendSkeleton.block(height: 64),
        SizedBox(height: TracendSpacing.xs),
        TracendSkeleton.block(height: 80),
        SizedBox(height: TracendSpacing.lg),
        TracendSkeleton.line(widthFactor: 0.4, height: 20),
        SizedBox(height: TracendSpacing.sm),
        TracendSkeleton.block(height: 260),
      ],
    ),
  );
}

/// The loaded brief, in reading order (UX_FLOWS.md §5): how recovered you
/// are and why (the tick ring), where the plan stands, sleep, load and fuel
/// at a glance, today's session with the coach's note, and the week so far.
class _BriefContent extends StatelessWidget {
  const _BriefContent({
    required this.brief,
    required this.targets,
    required this.meals,
    required this.latestDecision,
    required this.aiAllowed,
    required this.healthHistory,
    required this.syncing,
    required this.syncIssue,
    required this.onSync,
    required this.onOpenNutrition,
    required this.onOpenWorkout,
    required this.onCheckIn,
    required this.checkedIn,
    required this.offerCheckIn,
  });

  final DailyBrief brief;
  final Future<NutritionTargets?> targets;
  final Future<TodayMeals> meals;
  final Future<CoachDecision?> latestDecision;
  final bool aiAllowed;
  final Future<HealthHistory> healthHistory;
  final bool syncing;
  final String? syncIssue;
  final VoidCallback onSync;
  final VoidCallback? onOpenNutrition;
  final VoidCallback onOpenWorkout;
  final VoidCallback onCheckIn;
  final bool checkedIn;
  final bool offerCheckIn;

  @override
  Widget build(BuildContext context) {
    final colors = context.tracendColors;
    final today = DateTime.tryParse(brief.localDate) ?? DateTime.now();
    final plan = brief.plan;
    var index = 0;
    Widget enter(Widget child) =>
        MicroMotionEntrance(delay: MicroMotion.stagger(index++), child: child);
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        enter(
          TodayHero(
            brief: brief,
            onSync: onSync,
            syncing: syncing,
            syncIssue: syncIssue,
            checkedIn: checkedIn,
            offerCheckIn: offerCheckIn,
            onCheckIn: onCheckIn,
          ),
        ),
        if (plan != null) ...[
          const SizedBox(height: TracendSpacing.sm),
          enter(PlanProgressLine(plan: plan)),
        ],
        const SizedBox(height: TracendSpacing.md),
        enter(
          FutureBuilder<NutritionTargets?>(
            future: targets,
            builder: (context, targetSnapshot) => FutureBuilder<TodayMeals>(
              future: meals,
              builder: (context, mealSnapshot) => FutureBuilder<HealthHistory>(
                future: healthHistory,
                builder: (context, healthSnapshot) {
                  final todayMeals = mealSnapshot.data;
                  final targets = targetSnapshot.data;
                  return TodayTiles(
                    computed: brief.computed,
                    week: brief.week,
                    today: today,
                    consumed: brief.nutrition,
                    targets: targets,
                    fuelDay: todayMeals == null
                        ? null
                        : FuelDay.from(
                            proteinEaten:
                                ((brief.nutrition?['protein_g'] as num?) ?? 0)
                                    .toDouble(),
                            proteinTarget: targets?.protein,
                            schedule: todayMeals.schedule,
                            loggedMeals: todayMeals.meals,
                            now: DateTime.now(),
                          ),
                    sleepDay: _healthDay(healthSnapshot.data, today),
                    onLogMeal: onOpenNutrition,
                  );
                },
              ),
            ),
          ),
        ),
        const SizedBox(height: TracendSpacing.md),
        enter(
          FutureBuilder<CoachDecision?>(
            future: latestDecision,
            builder: (context, snapshot) => TodaySessionCard(
              brief: brief,
              decision: snapshot.data,
              aiAllowed: aiAllowed,
              onOpen: onOpenWorkout,
            ),
          ),
        ),
        if (brief.week.isNotEmpty) ...[
          const SizedBox(height: TracendSpacing.md),
          enter(YourWeekCard(week: brief.week, today: today)),
        ],
        const SizedBox(height: TracendSpacing.lg),
        Text(
          'Calculated from Apple Health and your logs. No AI in the numbers.',
          textAlign: TextAlign.center,
          style: Theme.of(
            context,
          ).textTheme.bodySmall?.copyWith(color: colors.textTertiary),
        ),
      ],
    );
  }

  /// Apple Health's summary for [day], when it has one.
  static HealthDay? _healthDay(HealthHistory? history, DateTime day) {
    if (history == null) return null;
    for (final entry in history.days) {
      final date = entry.date;
      if (date.year == day.year &&
          date.month == day.month &&
          date.day == day.day) {
        return entry;
      }
    }
    return null;
  }
}
