import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:tracend/app/environment.dart';
import 'package:tracend/app/theme/tracend_tokens.dart';
import 'package:tracend/features/account/account_screen.dart';
import 'package:tracend/features/account/notification_repository.dart';
import 'package:tracend/features/account/privacy_export_repository.dart';
import 'package:tracend/features/account/account_deletion_repository.dart';
import 'package:tracend/features/coach/coach_repository.dart';
import 'package:tracend/features/consent/ai_coaching_consent.dart';
import 'package:tracend/features/health/health_repository.dart';
import 'package:tracend/features/health/health_models.dart';
import 'package:tracend/features/nutrition/nutrition_repository.dart';
import 'package:tracend/features/train/workout_detail_screen.dart';
import 'package:tracend/features/train/workout_repository.dart';
import 'package:tracend/features/today/check_in_queue.dart';
import 'package:tracend/features/today/check_in_sheet.dart';
import 'package:tracend/features/today/daily_brief_repository.dart';
import 'package:tracend/features/today/widgets/check_in_prompt_bar.dart';
import 'package:tracend/features/today/widgets/coach_perspective_card.dart';
import 'package:tracend/features/today/widgets/metabolic_target_card.dart';
import 'package:tracend/features/today/widgets/recovery_readout_card.dart';
import 'package:tracend/features/today/widgets/session_plan_card.dart';
import 'package:tracend/features/today/widgets/sleep_architecture_card.dart';
import 'package:tracend/features/today/widgets/today_hero.dart';
import 'package:tracend/shared/widgets/micro_motion.dart';
import 'package:tracend/shared/widgets/pressable.dart';
import 'package:tracend/shared/widgets/tracend_scaffold.dart';
import 'package:tracend/shared/widgets/tracend_skeleton.dart';
import 'package:tracend/shared/widgets/tracend_toast.dart';
import 'package:tracend/shared/widgets/trajectory_trend.dart';

class TodayScreen extends StatefulWidget {
  const TodayScreen({
    required this.environment,
    this.onSignOut,
    this.workouts,
    this.health = const ManualHealthRepository(),
    this.coach = const FixtureCoachRepository(),
    this.brief = const FixtureDailyBriefRepository(),
    this.nutrition = const FixtureNutritionRepository(),
    this.queueFactory,
    this.checkInSender,
    this.onOpenProgress,
    this.onOpenNutrition,
    this.onOpenTrain,
    this.aiConsent,
    super.key,
  });

  final AppEnvironment environment;
  final Future<void> Function()? onSignOut;
  final WorkoutRepository? workouts;
  final HealthRepository health;
  final CoachRepository coach;
  final DailyBriefRepository brief;
  final NutritionRepository nutrition;

  /// Builds the pending-check-in replay queue. Defaults to the real
  /// SharedPreferences-backed queue; tests inject a fake.
  final CheckInQueue? Function()? queueFactory;

  /// Performs the `save_daily_check_in` RPC during replay. Defaults to the
  /// real Supabase client; tests inject a recording fake.
  final CheckInSend? checkInSender;

  /// Shell wiring: switch to the Progress tab ("More trends in Progress"
  /// under the 7-day trend).
  final VoidCallback? onOpenProgress;

  /// Shell wiring: switch to the Nutrition tab ("Log a meal").
  final VoidCallback? onOpenNutrition;

  /// Shell wiring: switch to the Train tab. Today's workout row opens Train
  /// when this is wired and the workout itself otherwise; the rest-day
  /// "See your week" action appears only when it is wired.
  final VoidCallback? onOpenTrain;

  /// The daily decision is generated by the AI provider only while this is
  /// granted. Null without a backend, where nothing is sent.
  final AiCoachingConsentController? aiConsent;

  @override
  State<TodayScreen> createState() => _TodayScreenState();
}

class _TodayScreenState extends State<TodayScreen> {
  late Future<HealthHistory> _healthHistory;
  late Future<DailyBrief> _brief;
  late Future<NutritionTargets?> _targets;
  late Future<CoachDecision?> _latestDecision;
  bool _syncing = false;

  /// What the last sync could not refresh, shown on the hero until a sync
  /// succeeds.
  String? _syncIssue;

  /// Auto health sync runs at most once per 30 minutes and never triggers a
  /// permission prompt: it fires only when a previous sync already succeeded.
  static const _autoSyncInterval = Duration(minutes: 30);

  bool get _aiAllowed => widget.aiConsent?.granted ?? true;

  /// Granting AI coaching brings today's decision without waiting for a sync.
  void _consentChanged() {
    setState(() {});
    if (_aiAllowed) _refreshDecisionAfterEvidence();
  }

  @override
  void didUpdateWidget(TodayScreen oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.aiConsent != widget.aiConsent) {
      oldWidget.aiConsent?.removeListener(_consentChanged);
      widget.aiConsent?.addListener(_consentChanged);
    }
  }

  @override
  void dispose() {
    widget.aiConsent?.removeListener(_consentChanged);
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    widget.aiConsent?.addListener(_consentChanged);
    _reloadHealth();
    _targets = widget.nutrition.loadTargets();
    _brief = widget.brief.load(DateTime.now());
    _latestDecision = widget.coach.loadLatest();
    _autoSyncHealthIfNeeded();
    _replayPendingCheckIn();
  }

  /// Deliver any check-in queued while offline: the sheet persists the
  /// envelope before its RPC, and this replays it with the same idempotency
  /// key (the server deduplicates). The stored answer day's date is sent as
  /// recorded — a check-in belongs to the day it was answered, never
  /// re-dated to today. Silent by design: on failure the envelope stays
  /// stored and the next launch retries; on success the brief reloads
  /// because the check-in now colors today's coaching context.
  Future<void> _replayPendingCheckIn() async {
    if (!widget.environment.hasSupabaseConfiguration) return;
    try {
      final queue = await _resolveQueue();
      if (queue == null) return;
      final outcome = await queue.replay(_replaySender);
      if (outcome == CheckInReplayOutcome.delivered && mounted) {
        setState(() {
          _brief = widget.brief.load(DateTime.now());
        });
        // The replayed check-in is new evidence: today's decision may have
        // been generated without it and must be refreshed.
        await _refreshDecisionAfterEvidence();
      }
    } on Exception {
      // Keep the envelope; retried on next launch.
    }
  }

  Future<bool> _replaySender(
    String localDate,
    String timezone,
    String idempotencyKey,
    Map<String, dynamic> payload,
  ) async {
    if (widget.checkInSender != null) {
      return widget.checkInSender!(
        localDate,
        timezone,
        idempotencyKey,
        payload,
      );
    }
    await Supabase.instance.client.rpc(
      'save_daily_check_in',
      params: {
        'local_date': localDate,
        'timezone': timezone,
        'idempotency_key': idempotencyKey,
        'payload': payload,
      },
    );
    return true;
  }

  Future<CheckInQueue?> _resolveQueue() async {
    if (widget.queueFactory != null) return widget.queueFactory!();
    final preferences = await SharedPreferences.getInstance();
    return CheckInQueue(
      preferences,
      userId: Supabase.instance.client.auth.currentUser?.id,
    );
  }

  void _reloadHealth() {
    _healthHistory = widget.health.loadHistory();
  }

  void _reloadBriefAndHealth() {
    _reloadHealth();
    setState(() {
      _brief = widget.brief.load(DateTime.now());
      _targets = widget.nutrition.loadTargets();
    });
  }

  Future<void> _autoSyncHealthIfNeeded() async {
    if (!widget.environment.hasSupabaseConfiguration) return;
    try {
      final status = await widget.health.loadStatus();
      final last = status.lastSuccessfulSync;
      if (last == null) return; // never connected -> manual via profile only
      if (DateTime.now().difference(last) < _autoSyncInterval) return;
      await widget.health.sync();
      if (mounted) _reloadBriefAndHealth();
    } catch (_) {
      // Silent: the hero sync button stays available for an explicit retry.
    }
  }

  /// Sync everything: Apple Health (when connected), the daily brief, and
  /// today's coaching decision. Each stage fails independently and the result
  /// message reports exactly what could not be refreshed — a HealthKit read
  /// that returns `unavailable` counts as a failure, and a never-connected
  /// Apple Health is reported as skipped, never as "up to date".
  Future<void> _syncEverything() async {
    if (_syncing) return;
    setState(() => _syncing = true);
    final failures = <String>[];
    var healthSkipped = false;
    try {
      try {
        final status = await widget.health.loadStatus();
        if (status.lastSuccessfulSync != null) {
          final synced = await widget.health.sync();
          if (synced.state == HealthConnectionState.unavailable) {
            failures.add('Apple Health');
          }
        } else {
          healthSkipped = true;
        }
      } catch (_) {
        failures.add('Apple Health');
      }
      if (!mounted) return;
      _reloadBriefAndHealth();
      if (widget.environment.hasSupabaseConfiguration) {
        try {
          final latest = await widget.coach.loadLatest();
          final today = _dateKey(DateTime.now());
          final citedCheckInMissing =
              latest != null &&
              latest.localDate == today &&
              latest.missingData.contains('recovery_check_in');
          if (_aiAllowed &&
              (latest == null ||
                  latest.localDate != today ||
                  citedCheckInMissing)) {
            // Same freshness rule as _refreshDecisionAfterEvidence: a
            // decision generated before the check-in landed is stale.
            await widget.coach.generate();
          }
          if (!mounted) return;
          setState(() {
            _latestDecision = widget.coach.loadLatest();
          });
        } catch (_) {
          failures.add('coach decision');
        }
      }
      if (!mounted) return;
      final String message;
      if (failures.isNotEmpty) {
        message = 'Synced, but unavailable: ${failures.join(', ')}.';
      } else if (healthSkipped) {
        message =
            'Synced. Apple Health is not connected — set it up in your profile.';
      } else {
        message = 'Everything is up to date.';
      }
      setState(() {
        _syncIssue = failures.isEmpty
            ? null
            : 'Could not refresh ${failures.join(' or ')}. Pull down or tap '
                  'Sync to try again.';
      });
      TracendToast.show(
        context,
        message,
        icon: failures.isEmpty
            ? CupertinoIcons.checkmark_alt
            : CupertinoIcons.exclamationmark_triangle,
      );
    } finally {
      if (mounted) setState(() => _syncing = false);
    }
  }

  String _dateKey(DateTime value) =>
      '${value.year.toString().padLeft(4, '0')}-'
      '${value.month.toString().padLeft(2, '0')}-'
      '${value.day.toString().padLeft(2, '0')}';

  /// Refreshes the coaching decision after new evidence arrived.
  ///
  /// The daily decision generates once per day, but it can be generated
  /// before the morning check-in — in that state the policy permits only
  /// gather-data actions and cites `recovery_check_in` as missing, and the
  /// card would keep saying "gather data" all day even after the check-in
  /// lands (the bar reads the live table, so the two contradicted each
  /// other). When today's decision cited the check-in as missing, a new
  /// decision is generated (new idempotency key → new audited row); the
  /// guardrails are unchanged, only the evidence is fresh. Failures are
  /// silent — the stale decision remains valid coaching.
  Future<void> _refreshDecisionAfterEvidence() async {
    if (!widget.environment.hasSupabaseConfiguration || !_aiAllowed) return;
    try {
      final latest = await widget.coach.loadLatest();
      final today = _dateKey(DateTime.now());
      final citedCheckInMissing =
          latest != null &&
          latest.localDate == today &&
          latest.missingData.contains('recovery_check_in');
      // Checked again after the load: Today stays mounted while AI coaching
      // is turned off in Account, so the answer can change during the wait.
      if (_aiAllowed &&
          (latest == null ||
              latest.localDate != today ||
              citedCheckInMissing)) {
        await widget.coach.generate();
      }
      if (!mounted) return;
      setState(() {
        _latestDecision = widget.coach.loadLatest();
      });
    } catch (_) {
      // Stale-but-valid decision stays on screen; the hero sync retries.
    }
  }

  Future<void> _openCheckIn() async {
    await showCheckInSheet(
      context,
      widget.environment,
      sender: widget.checkInSender,
    );
    if (mounted) {
      setState(() {
        _brief = widget.brief.load(DateTime.now());
      });
      await _refreshDecisionAfterEvidence();
    }
  }

  /// Opens the brief's workout: the one planned for the date the brief was
  /// loaded for. A fixture brief carries no workout id, so its repository's
  /// workout opens instead.
  Future<void> _openWorkout(DailyBrief brief) async {
    final row = brief.workout;
    PlannedWorkout? workout;
    if (row != null && row['id'] is String) {
      workout = PlannedWorkout.fromHubJson(row);
    } else {
      try {
        workout = await widget.workouts?.loadTodayWorkout();
      } catch (e) {
        debugPrint('Non-critical error: $e');
      }
    }
    if (workout == null || !mounted) return;
    final completed = await Navigator.of(context).push<bool>(
      CupertinoPageRoute(
        builder: (_) => WorkoutDetailScreen(
          repository: widget.workouts,
          workout: workout,
          sessionDate: DateTime.tryParse(brief.localDate) ?? DateTime.now(),
        ),
      ),
    );
    if (completed == true && mounted) {
      setState(() => _brief = widget.brief.load(DateTime.now()));
    }
  }

  void _openAccount() => Navigator.of(context).push<void>(
    CupertinoPageRoute(
      builder: (_) => AccountScreen(
        environment: widget.environment,
        onSignOut: widget.onSignOut,
        health: widget.health,
        coach: widget.coach,
        notifications: widget.environment.hasSupabaseConfiguration
            ? SupabaseNotificationRepository(Supabase.instance.client)
            : const FixtureNotificationRepository(),
        exports: widget.environment.hasSupabaseConfiguration
            ? SupabasePrivacyExportRepository(Supabase.instance.client)
            : const FixturePrivacyExportRepository(),
        deletion: widget.environment.hasSupabaseConfiguration
            ? SupabaseAccountDeletionRepository(Supabase.instance.client)
            : const FixtureAccountDeletionRepository(),
        aiConsent: widget.aiConsent,
      ),
    ),
  );

  @override
  Widget build(BuildContext context) {
    final now = DateTime.now();
    // "Good afternoon" cannot fit a 320pt screen at the largest text sizes
    // without breaking a word, so there the title is "Today" and the
    // greeting moves into the subtitle.
    final compactTitle = MediaQuery.textScalerOf(context).scale(34) > 48;
    // Today's pressable rows and cards ink on this, so the screen also works
    // when it is mounted without a Scaffold.
    return Material(
      type: MaterialType.transparency,
      child: TracendScrollView(
        title: compactTitle ? 'Today' : _greeting(now),
        subtitle: compactTitle
            ? '${_greeting(now)}, ${_formattedDate(now)}'
            : _formattedDate(now),
        onRefresh: _syncEverything,
        trailing: _AccountButton(onPressed: _openAccount),
        children: [
          FutureBuilder<DailyBrief>(
            future: _brief,
            builder: (context, snapshot) {
              // FutureBuilder retains the previous data when the future is
              // swapped (check-in / health sync reloads). Prefer it over the
              // waiting state so _BriefContent stays mounted: stagger
              // entrances don't replay and score count-ups animate on change.
              final brief = snapshot.data;
              if (brief != null) {
                return _BriefContent(
                  brief: brief,
                  targets: _targets,
                  latestDecision: _latestDecision,
                  aiAllowed: _aiAllowed,
                  healthHistory: _healthHistory,
                  syncing: _syncing,
                  syncIssue: _syncIssue,
                  onSync: _syncEverything,
                  onOpenProgress: widget.onOpenProgress,
                  onOpenNutrition: widget.onOpenNutrition,
                  onOpenWorkout:
                      widget.onOpenTrain ?? () => _openWorkout(brief),
                  onOpenWeek: widget.onOpenTrain,
                  onCheckIn: _openCheckIn,
                );
              }
              if (snapshot.connectionState == ConnectionState.waiting) {
                return const _BriefSkeleton();
              }
              return TracendCard(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Use your approved plan.',
                      style: Theme.of(context).textTheme.headlineSmall,
                    ),
                    const SizedBox(height: TracendSpacing.xs),
                    const Text(
                      'The daily brief is unavailable. Workout and meal logging '
                      'remain available. Pull down to try again.',
                    ),
                  ],
                ),
              );
            },
          ),
        ],
      ),
    );
  }

  /// A plain greeting by the time of day; no name is invented.
  String _greeting(DateTime now) {
    if (now.hour >= 5 && now.hour < 12) return 'Good morning';
    if (now.hour >= 12 && now.hour < 18) return 'Good afternoon';
    return 'Good evening';
  }

  String _formattedDate(DateTime value) {
    const weekdays = [
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
      'Sunday',
    ];
    const months = [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ];
    return '${weekdays[value.weekday - 1]} ${value.day} '
        '${months[value.month - 1]}';
  }
}

/// The account control in the large title: a round avatar in a 44pt
/// target, named "Open account" for VoiceOver and as its tooltip.
class _AccountButton extends StatelessWidget {
  const _AccountButton({required this.onPressed});

  final VoidCallback onPressed;

  @override
  Widget build(BuildContext context) {
    final colors = context.tracendColors;
    return Tooltip(
      message: 'Open account',
      excludeFromSemantics: true,
      child: Pressable(
        onTap: onPressed,
        semanticLabel: 'Open account',
        borderRadius: BorderRadius.circular(TracendRadii.pill),
        child: SizedBox.square(
          dimension: 44,
          child: Center(
            child: DecoratedBox(
              decoration: BoxDecoration(
                color: colors.surfaceRaised,
                shape: BoxShape.circle,
              ),
              child: SizedBox.square(
                dimension: 36,
                child: Icon(
                  CupertinoIcons.person_fill,
                  size: 19,
                  color: colors.textSecondary,
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

/// Today in the shape it is about to take: the hero, the check-in and
/// workout rows, and the trend. One label for VoiceOver.
class _BriefSkeleton extends StatelessWidget {
  const _BriefSkeleton();

  @override
  Widget build(BuildContext context) => Semantics(
    label: 'Loading Today',
    container: true,
    child: const Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        TracendSkeleton.block(height: 248),
        SizedBox(height: TracendSpacing.xs),
        TracendSkeleton.block(height: 64),
        SizedBox(height: TracendSpacing.xs),
        TracendSkeleton.block(height: 80),
        SizedBox(height: TracendSpacing.lg),
        TracendSkeleton.line(widthFactor: 0.4, height: 20),
        SizedBox(height: TracendSpacing.sm),
        TracendSkeleton.block(height: 260),
      ],
    ),
  );
}

/// The loaded brief, in reading order (UX_FLOWS.md §5): the verdict, the
/// check-in and today's workout, food and the coach note, then the evidence
/// (the 7-day trend, recovery drivers, sleep).
class _BriefContent extends StatelessWidget {
  const _BriefContent({
    required this.brief,
    required this.targets,
    required this.latestDecision,
    required this.aiAllowed,
    required this.healthHistory,
    required this.syncing,
    required this.syncIssue,
    required this.onSync,
    required this.onOpenProgress,
    required this.onOpenNutrition,
    required this.onOpenWorkout,
    required this.onOpenWeek,
    required this.onCheckIn,
  });

  final DailyBrief brief;
  final Future<NutritionTargets?> targets;
  final Future<CoachDecision?> latestDecision;
  final bool aiAllowed;
  final Future<HealthHistory> healthHistory;
  final bool syncing;
  final String? syncIssue;
  final VoidCallback onSync;
  final VoidCallback? onOpenProgress;
  final VoidCallback? onOpenNutrition;
  final VoidCallback onOpenWorkout;
  final VoidCallback? onOpenWeek;
  final VoidCallback onCheckIn;

  @override
  Widget build(BuildContext context) {
    final computed = brief.computed;
    var index = 0;
    Widget enter(Widget child) =>
        MicroMotionEntrance(delay: MicroMotion.stagger(index++), child: child);
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        enter(
          TodayHero(
            brief: brief,
            onSync: onSync,
            syncing: syncing,
            syncIssue: syncIssue,
          ),
        ),
        const SizedBox(height: TracendSpacing.xs),
        enter(
          CheckInPromptBar(
            onCheckIn: onCheckIn,
            completed: brief.checkIn != null,
          ),
        ),
        const SizedBox(height: TracendSpacing.xs),
        enter(
          SessionPlanCard(
            workout: brief.workout,
            acwr: computed?.scores.acwr,
            onOpen: onOpenWorkout,
            onOpenWeek: onOpenWeek,
          ),
        ),
        enter(
          Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              const SectionLabel('Food'),
              FutureBuilder<NutritionTargets?>(
                future: targets,
                builder: (context, snapshot) => MetabolicTargetCard(
                  consumed: brief.nutrition,
                  targets: snapshot.data,
                  onLog: onOpenNutrition,
                ),
              ),
            ],
          ),
        ),
        enter(
          Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              const SectionLabel('Coach note'),
              _CoachPerspectiveSection(
                latestDecision: latestDecision,
                aiAllowed: aiAllowed,
              ),
            ],
          ),
        ),
        enter(
          Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              const SectionLabel('Last 7 days'),
              FutureBuilder<HealthHistory>(
                future: healthHistory,
                builder: (context, snapshot) {
                  final history = snapshot.data;
                  if (history != null) {
                    return TrajectoryTrend(history: history);
                  }
                  if (snapshot.connectionState == ConnectionState.waiting) {
                    return Semantics(
                      label: 'Loading the 7-day trend',
                      container: true,
                      child: const TracendSkeleton.block(height: 300),
                    );
                  }
                  return TracendCard(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'Health trend unavailable',
                          style: Theme.of(context).textTheme.titleSmall,
                        ),
                        const SizedBox(height: TracendSpacing.xxs),
                        Text(
                          'Pull down or tap Sync to refresh the Apple Health '
                          'summary.',
                          style: Theme.of(context).textTheme.bodySmall,
                        ),
                      ],
                    ),
                  );
                },
              ),
              // Below the card rather than as a section-label action, which
              // cannot shrink at the largest text sizes on a 320pt screen.
              if (onOpenProgress != null)
                Align(
                  alignment: AlignmentDirectional.centerStart,
                  child: TextButton(
                    onPressed: onOpenProgress,
                    child: const Text('More trends in Progress'),
                  ),
                ),
            ],
          ),
        ),
        if (computed?.scores.recoveryBreakdown != null)
          enter(
            Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                const SectionLabel('Recovery drivers'),
                RecoveryReadoutCard(computed: computed!),
              ],
            ),
          ),
        if (computed != null)
          enter(
            Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                const SectionLabel('Sleep'),
                SleepArchitectureCard(computed: computed),
              ],
            ),
          ),
      ],
    );
  }
}

/// Coach note: renders the latest [CoachDecision] (the real training and
/// nutrition summaries and confidence). The future is owned by the screen
/// state so the sync pipeline can refresh it after generating a decision.
/// Falls back to an honest prompt when no decision exists.
class _CoachPerspectiveSection extends StatelessWidget {
  const _CoachPerspectiveSection({
    required this.latestDecision,
    required this.aiAllowed,
  });

  final Future<CoachDecision?> latestDecision;
  final bool aiAllowed;

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<CoachDecision?>(
      future: latestDecision,
      builder: (context, snapshot) {
        final decision = snapshot.data;
        if (decision == null) {
          return TracendCard(
            child: Text(
              aiAllowed
                  ? 'Tap Sync to generate an evidence-backed daily decision.'
                  : 'AI coaching is off, so no daily decision is generated. Turn it on in Account.',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
          );
        }
        return CoachPerspectiveCard(decision: decision);
      },
    );
  }
}
