begin;
select plan(23);
select has_column('public','exercise_performances','performance_kind','performance kind is persisted');
select has_column('public','exercise_performances','performed_name','performed identity is separate');
select has_column('public','exercise_performances','substitution_reason','substitution reason is persisted');
select has_column('public','workout_sessions','logging_completeness','logging coverage is explicit');
select has_column('public','workout_sessions','correction_status','correction state is explicit');
select has_function('public','get_my_workout_session',array['uuid','date'],'resumable session RPC exists');
select has_function('public','correct_completed_workout',array['uuid','timestamp with time zone','timestamp with time zone','text','uuid'],'audited correction RPC exists');
select has_function('public','get_my_workout_repair_candidates',array[]::text[],'repair candidate RPC exists');
select has_table('public','health_workout_references','bounded HealthKit workout references exist');
select has_table('public','workout_reconciliations','workout reconciliation records exist');
select has_function('public','persist_health_sync_v2','atomic health sync v2 exists');
select has_function('public','respond_workout_reconciliation',array['uuid','boolean'],'owner reconciliation response exists');
select has_table('public','coach_context_snapshots','immutable context snapshots exist');
select has_column('public','coach_context_snapshots','context_checksum','context checksum is persisted');
select has_function('public','prepare_coach_chat_v3',array['uuid','uuid','text','text','uuid'],'Coach Context v2 preparation exists');
select is((select relrowsecurity from pg_class where oid='public.health_workout_references'::regclass),true,'HealthKit workout RLS enabled');
select is((select relforcerowsecurity from pg_class where oid='public.health_workout_references'::regclass),true,'HealthKit workout RLS forced');
select is((select relrowsecurity from pg_class where oid='public.workout_reconciliations'::regclass),true,'reconciliation RLS enabled');
select is((select relforcerowsecurity from pg_class where oid='public.coach_context_snapshots'::regclass),true,'context snapshot RLS forced');
select is((select count(*)::integer from information_schema.role_table_grants where table_schema='public' and table_name='coach_context_snapshots' and grantee='anon'),0,'anonymous context access denied');
select has_function('public','get_my_workout_reconciliation_candidates','ranked reconciliation candidates RPC exists');
select has_function('public','respond_workout_reconciliation',array['uuid','boolean'],'transactional reconciliation response exists');
select has_function('public','save_body_measurement',array['date','numeric','numeric','numeric','numeric','numeric','numeric'],'same-day measurement amendment RPC exists');
select * from finish();
rollback;
