-- Pass 5 — reference parity (2026-09-08, hardened 2026-09-09).
--
-- The Dart reference implementation (test/reference/recovery_reference.dart,
-- written from docs/ALGORITHMS.md, not from SQL) and the production SQL
-- (compute_user_baselines / compute_daily_metrics, migration
-- 20260907160000) must produce the same numbers on the same inputs. This
-- test seeds the shared oracle fixtures (test/reference/fixtures/*.json —
-- shipped into the container at /fixtures by scripts/test-db.sh) into the
-- database and asserts the SQL output matches the reference's pins.
--
-- TWO assertion layers, both mandatory:
-- 1. The `expected` oracle block embedded in every fixture (generated by
--    tool/generate_expected.dart from the Dart reference). assert_expected()
--    runs the seeded fixture through compute_daily_metrics and compares
--    every scored output — recovery, the five z-scores, sleep quality, the
--    breakdown-exposure rule, the four sub-scores, breakdown-missing, debt,
--    strain, ACWR, monotony, data confidence, missing components — at the
--    SQL's own rounding scale. A sign flip, a weight typo, or a gate change
--    in EITHER implementation breaks these rows. That is the drift alarm.
-- 2. The independent hand-computed anchors (62, -0.294, 1.95, 2.27, 85.6,
--    the x3 ln-invariance twin) — derived outside both implementations,
--    so the oracle blocks can never go quietly circular.
--
-- Sub-score exposure rule: the SQL emits the sleep_breakdown object (and
-- with it the individual sub-scores) ONLY when all four subs are
-- computable; the reference exposes each computable sub individually. So
-- the SQL side pins the exposure rule itself (breakdown present ⟺ all
-- four expected subs non-null), compares each sub within ε when exposed,
-- and pins the renormalized composite + sleep_breakdown_missing on
-- partial nights — which still catches a duration/consistency drift
-- through the composite it feeds.
--
-- Seeding pattern (the fixtures are client-side psql variables, so each
-- block does its own \set + seeding + assertions):
--   \set fixture_json `cat /fixtures/<name>.json`
--   select pg_temp.seed_fixture(:'fixture_json', '<user>');
--   select * from pg_temp.assert_expected(:'fixture_json'::jsonb, '<user>', '<label>');
--
-- Rounding contract: the SQL emits z-scores rounded to 3 decimals, sleep
-- sub-scores to 1, ACWR/monotony/strain to 2, recovery/quality/debt as
-- integers; the expected blocks carry the same scales. z/sub comparisons
-- use ε 0.005 / 0.05; integers compare exactly; a NULL on either side of
-- an exact compare uses the -9999 sentinel (outside every field's range).

begin;
select plan(259);

-- The auth_user_create_account trigger auto-inserts the user_accounts
-- row on the auth.users insert — no explicit account insert needed (and
-- an explicit one would collide on id).
create function pg_temp.seed_user(v_user uuid) returns void language plpgsql as $$
begin
  insert into auth.users(id, role) values (v_user, 'authenticated');
end $$;

-- Sessions need the plan/version/workout FK chain.
create function pg_temp.seed_sessions(
  v_user uuid, v_fix jsonb
) returns void language plpgsql as $$
declare
  s jsonb;
  v_plan uuid := gen_random_uuid();
  version_id uuid := gen_random_uuid();
  workout_id uuid := gen_random_uuid();
begin
  if jsonb_array_length(v_fix->'sessions') = 0 then return; end if;

  insert into public.training_plans(id, user_id, title, source)
  values (v_plan, v_user, 'Parity plan', 'imported');
  insert into public.training_plan_versions(
    id, user_id, plan_id, version_number, status, block_weeks, sessions_per_week,
    prescription, rationale, approved_at, effective_date)
  values (version_id, v_user, v_plan, 1, 'active', 8, 6, '{}',
    'Approved plan', now(), current_date - 30);
  insert into public.planned_workouts(
    id, user_id, plan_version_id, name, workout_order, preferred_weekday,
    objective, estimated_minutes, warm_up_guidance, cool_down_guidance)
  values (workout_id, v_user, version_id, 'Parity session', 1, 1, 'Load',
    60, 'Warm up', 'Cool down');

  for s in select value from jsonb_array_elements(v_fix->'sessions') loop
    insert into public.workout_sessions(
      user_id, plan_version_id, planned_workout_id, state, local_date, timezone,
      idempotency_key, session_effort, duration_seconds, logging_completeness,
      completed_at)
    values (v_user, version_id, workout_id, 'completed',
      (s->>'date')::date, 'Asia/Kolkata', gen_random_uuid(),
      (s->>'effort')::numeric, (s->>'duration_seconds')::int, 1.0, now());
  end loop;
end $$;

-- Health days. present_types is derived from the keys actually present
-- (array_remove of case-when nulls), which the parity assertions never
-- read — they read the computed columns.
create function pg_temp.seed_health(
  v_user uuid, v_fix jsonb
) returns void language plpgsql as $$
declare
  d jsonb;
  v_types text[];
begin
  for d in select value from jsonb_array_elements(v_fix->'health_days') loop
    v_types := array_remove(array[
      case when d ? 'hrv_ms' then 'hrv_sdnn' end,
      case when d ? 'resting_hr_bpm' then 'resting_heart_rate' end,
      case when d ? 'sleep_minutes' then 'sleep' end,
      case when d ? 'resp_rate_bpm' then 'resp_rate' end,
      case when d ? 'weight_kg' then 'weight' end
    ], null);

    insert into public.daily_health_summaries(
      user_id, local_date, timezone, present_types, source_refs,
      source_checksum, completeness, observed_through, last_synced_at,
      hrv_value_ms, hrv_metric, hrv_unit,
      resting_heart_rate_bpm, respiratory_rate_bpm,
      sleep_minutes, sleep_awake_minutes, sleep_deep_minutes, sleep_rem_minutes
    )
    values (
      v_user, (d->>'date')::date, 'Asia/Kolkata', v_types,
      '[]'::jsonb, md5(random()::text) || md5(random()::text),
      'partial', now(), now(),
      nullif(d->>'hrv_ms','')::numeric,
      case when d ? 'hrv_ms' then 'sdnn' end,
      case when d ? 'hrv_ms' then 'ms' end,
      nullif(d->>'resting_hr_bpm','')::numeric,
      nullif(d->>'resp_rate_bpm','')::numeric,
      nullif(d->>'sleep_minutes','')::int,
      nullif(d->>'sleep_awake_minutes','')::int,
      nullif(d->>'sleep_deep_minutes','')::int,
      nullif(d->>'sleep_rem_minutes','')::int
    );
  end loop;
end $$;

create function pg_temp.seed_weights(
  v_user uuid, v_fix jsonb
) returns void language plpgsql as $$
declare
  w jsonb;
begin
  for w in select value from jsonb_array_elements(v_fix->'weight_days') loop
    insert into public.body_measurements(user_id, measured_on, source, weight_kg)
    values (v_user, (w->>'date')::date, 'manual', (w->>'weight_kg')::numeric);
  end loop;
end $$;

-- Seed one fixture (user id per fixture; fixtures run in their own
-- transaction, so ids never collide across files).
create function pg_temp.seed_fixture(v_fix jsonb, v_user uuid)
returns void language plpgsql as $$
begin
  perform pg_temp.seed_user(v_user);
  perform pg_temp.seed_health(v_user, v_fix);
  perform pg_temp.seed_sessions(v_user, v_fix);
  perform pg_temp.seed_weights(v_user, v_fix);
end $$;

-- ─────────────────────────────────────────────────────────────────────────
-- Layer 1 — the expected-oracle drift alarm.
--
-- Runs the seeded fixture through the production SQL and compares every
-- scored output against the fixture's embedded `expected` block at the
-- SQL's own rounding scale. One TAP row per field (pgTAP test functions
-- return text; this set-returning helper emits them through `return next`).
-- ─────────────────────────────────────────────────────────────────────────

create function pg_temp.assert_expected(v_fix jsonb, v_user uuid, v_name text)
returns setof text language plpgsql as $$
declare
  v_out jsonb;
  v_e jsonb := v_fix->'expected';
  v_s jsonb;
  v_b jsonb;
begin
  v_out := public.compute_daily_metrics(
    v_user, (v_fix->>'target_date')::date, 'Asia/Kolkata');
  v_s := v_out->'scores';
  v_b := v_s->'recovery_breakdown';

  -- Integers (SQL rounds these itself; expected blocks carry the same
  -- scale). -9999 sentinel = null on either side, outside every range.
  return next is(
    coalesce((v_s->>'recovery')::numeric, -9999),
    coalesce((v_e->>'recovery')::numeric, -9999),
    v_name || ': recovery');

  return next is(
    coalesce((v_s->>'sleep_quality')::numeric, -9999),
    coalesce((v_e->>'sleep_quality')::numeric, -9999),
    v_name || ': sleep_quality');

  return next is(
    coalesce((v_s->>'sleep_debt_minutes')::numeric, -9999),
    coalesce((v_e->>'sleep_debt_minutes')::numeric, -9999),
    v_name || ': sleep_debt_minutes');

  return next is(
    coalesce((v_s->>'daily_strain')::numeric, -9999),
    coalesce((v_e->>'daily_strain')::numeric, -9999),
    v_name || ': daily_strain');

  return next is(
    coalesce((v_s->>'acwr')::numeric, -9999),
    coalesce((v_e->>'acwr')::numeric, -9999),
    v_name || ': acwr');

  return next is(
    coalesce((v_s->>'training_monotony')::numeric, -9999),
    coalesce((v_e->>'monotony')::numeric, -9999),
    v_name || ': training_monotony');

  -- Text.
  return next is(
    v_out->>'data_confidence',
    v_e->>'data_confidence',
    v_name || ': data_confidence');

  -- Missing components: exact array equality (order + duplicates).
  return next is(
    v_b->'missing_components' = v_e->'missing_components',
    true,
    v_name || ': missing_components');

  -- Z-scores (SQL emits all five keys, rounded to 3 decimals).
  return next ok(
    abs(coalesce((v_b->>'hrv_z')::numeric, -9999)
      - coalesce((v_e->>'hrv_z')::numeric, -9999)) <= 0.005,
    format('%s: hrv_z (sql %s vs expected %s)', v_name,
      coalesce(v_b->>'hrv_z', 'absent'), coalesce(v_e->>'hrv_z', 'absent')));

  return next ok(
    abs(coalesce((v_b->>'rhr_z')::numeric, -9999)
      - coalesce((v_e->>'rhr_z')::numeric, -9999)) <= 0.005,
    format('%s: rhr_z (sql %s vs expected %s)', v_name,
      coalesce(v_b->>'rhr_z', 'absent'), coalesce(v_e->>'rhr_z', 'absent')));

  return next ok(
    abs(coalesce((v_b->>'sleep_z')::numeric, -9999)
      - coalesce((v_e->>'sleep_z')::numeric, -9999)) <= 0.005,
    format('%s: sleep_z (sql %s vs expected %s)', v_name,
      coalesce(v_b->>'sleep_z', 'absent'), coalesce(v_e->>'sleep_z', 'absent')));

  return next ok(
    abs(coalesce((v_b->>'resp_rate_z')::numeric, -9999)
      - coalesce((v_e->>'resp_rate_z')::numeric, -9999)) <= 0.005,
    format('%s: resp_rate_z (sql %s vs expected %s)', v_name,
      coalesce(v_b->>'resp_rate_z', 'absent'),
      coalesce(v_e->>'resp_rate_z', 'absent')));

  return next ok(
    abs(coalesce((v_b->>'prev_strain_z')::numeric, -9999)
      - coalesce((v_e->>'prev_strain_z')::numeric, -9999)) <= 0.005,
    format('%s: prev_strain_z (sql %s vs expected %s)', v_name,
      coalesce(v_b->>'prev_strain_z', 'absent'),
      coalesce(v_e->>'prev_strain_z', 'absent')));

  -- Sub-score exposure: the SQL emits the breakdown object (and the
  -- individual subs inside it) only when ALL FOUR subs are computable.
  -- The expected block exposes each computable sub independently, so
  -- this row pins the exposure rule itself. Presence is read via ->>
  -- (a JSON null value flattens to SQL NULL there; -> keeps it as a
  -- non-null jsonb, which would make the check lie).
  return next is(
    (v_s->>'sleep_breakdown') is not null,
    (v_e->>'duration_score') is not null
      and (v_e->>'efficiency_score') is not null
      and (v_e->>'restorative_score') is not null
      and (v_e->>'consistency_score') is not null,
    v_name || ': sleep_breakdown exposure (all four subs or none)');

  -- Sub-scores, compared only when exposed (partial nights are pinned
  -- through the composite + breakdown-missing rows above and below).
  return next ok(
    case when (v_s->>'sleep_breakdown') is null then true
      else abs((v_s->'sleep_breakdown'->>'duration_score')::numeric
        - (v_e->>'duration_score')::numeric) <= 0.05 end,
    format('%s: duration_score (sql %s vs expected %s)', v_name,
      coalesce(v_s->'sleep_breakdown'->>'duration_score', 'not exposed'),
      coalesce(v_e->>'duration_score', 'absent')));

  return next ok(
    case when (v_s->>'sleep_breakdown') is null then true
      else abs((v_s->'sleep_breakdown'->>'efficiency_score')::numeric
        - (v_e->>'efficiency_score')::numeric) <= 0.05 end,
    format('%s: efficiency_score (sql %s vs expected %s)', v_name,
      coalesce(v_s->'sleep_breakdown'->>'efficiency_score', 'not exposed'),
      coalesce(v_e->>'efficiency_score', 'absent')));

  return next ok(
    case when (v_s->>'sleep_breakdown') is null then true
      else abs((v_s->'sleep_breakdown'->>'restorative_score')::numeric
        - (v_e->>'restorative_score')::numeric) <= 0.05 end,
    format('%s: restorative_score (sql %s vs expected %s)', v_name,
      coalesce(v_s->'sleep_breakdown'->>'restorative_score', 'not exposed'),
      coalesce(v_e->>'restorative_score', 'absent')));

  return next ok(
    case when (v_s->>'sleep_breakdown') is null then true
      else abs((v_s->'sleep_breakdown'->>'consistency_score')::numeric
        - (v_e->>'consistency_score')::numeric) <= 0.05 end,
    format('%s: consistency_score (sql %s vs expected %s)', v_name,
      coalesce(v_s->'sleep_breakdown'->>'consistency_score', 'not exposed'),
      coalesce(v_e->>'consistency_score', 'absent')));

  -- breakdown-missing: an absent key and a JSON null are the same state
  -- here (no valid sleep night); normalize both sides to jsonb 'null'
  -- before comparing, then compare as jsonb (array order preserved).
  return next is(
    (coalesce(v_s->'sleep_breakdown_missing', 'null'::jsonb))
      is not distinct from
    (coalesce(v_e->'sleep_breakdown_missing', 'null'::jsonb)),
    true,
    v_name || ': sleep_breakdown_missing');
end $$;

-- ─────────────────────────────────────────────────────────────────────────
-- Layer 2 — independent hand-computed anchors (never delete these).
-- ─────────────────────────────────────────────────────────────────────────

-- Fixture 1: owner_day_strain_only (the 2026-08-25 production day).
-- Hand pins: recovery 62, prev_strain_z -0.294, four health missing.

\set fixture_json `cat /fixtures/owner_day_strain_only.json`
select pg_temp.seed_fixture(:'fixture_json'::jsonb,
  '5a5a5a5a-0001-4001-8001-000000000001');
select * from pg_temp.assert_expected(
  :'fixture_json'::jsonb, '5a5a5a5a-0001-4001-8001-000000000001',
  'owner day');

select is(
  (public.compute_daily_metrics(
    '5a5a5a5a-0001-4001-8001-000000000001', '2026-09-08'::date, 'Asia/Kolkata'
  )->'scores'->>'recovery'),
  '62',
  'anchor 1: owner strain-only day — SQL recovery 62 (recovery_honesty anchor)');

select is(
  (public.compute_daily_metrics(
    '5a5a5a5a-0001-4001-8001-000000000001', '2026-09-08'::date, 'Asia/Kolkata'
  )->'scores'->'recovery_breakdown'->>'prev_strain_z')::numeric,
  -0.294,
  'anchor 2: prev_strain_z -0.294 (hand-computed: prev7 10, avg28 11.5, sd sqrt(26))');

-- Fixture 2: zero_data.
\set fixture_json `cat /fixtures/zero_data.json`
select pg_temp.seed_fixture(:'fixture_json'::jsonb,
  '5a5a5a5a-0002-4001-8002-000000000002');
select * from pg_temp.assert_expected(
  :'fixture_json'::jsonb, '5a5a5a5a-0002-4001-8002-000000000002',
  'zero data');

select ok(
  (public.compute_daily_metrics(
    '5a5a5a5a-0002-4001-8002-000000000002', '2026-09-08'::date, 'Asia/Kolkata'
  )->'scores'->>'recovery') is null,
  'anchor 3: zero data — no recovery fabricated from nothing');

-- Fixture 3: hrv_only_history.
\set fixture_json `cat /fixtures/hrv_only_history.json`
select pg_temp.seed_fixture(:'fixture_json'::jsonb,
  '5a5a5a5a-0003-4001-8003-000000000003');
select * from pg_temp.assert_expected(
  :'fixture_json'::jsonb, '5a5a5a5a-0003-4001-8003-000000000003',
  'hrv only');

-- Fixture 4: hrv_cold_start_today_only.
\set fixture_json `cat /fixtures/hrv_cold_start_today_only.json`
select pg_temp.seed_fixture(:'fixture_json'::jsonb,
  '5a5a5a5a-0004-4001-8004-000000000004');
select * from pg_temp.assert_expected(
  :'fixture_json'::jsonb, '5a5a5a5a-0004-4001-8004-000000000004',
  'hrv cold start');

-- assert_expected's compute call folds the baselines, so the cold-start
-- row is already materialized for the anchor below.
select is(
  (select n_observations from public.user_baselines
   where user_id = '5a5a5a5a-0004-4001-8004-000000000004'
     and metric_name = 'hrv_sdnn_ms'),
  1,
  'anchor 4: cold baseline n_observations = 1 (below the 3-observation gate)');

-- Fixture 5: full_data_day.
\set fixture_json `cat /fixtures/full_data_day.json`
select pg_temp.seed_fixture(:'fixture_json'::jsonb,
  '5a5a5a5a-0005-4001-8005-000000000005');
select * from pg_temp.assert_expected(
  :'fixture_json'::jsonb, '5a5a5a5a-0005-4001-8005-000000000005',
  'full data');

-- Fixture 6: long_sleep_resp_day.
\set fixture_json `cat /fixtures/long_sleep_resp_day.json`
select pg_temp.seed_fixture(:'fixture_json'::jsonb,
  '5a5a5a5a-0006-4001-8006-000000000006');
select * from pg_temp.assert_expected(
  :'fixture_json'::jsonb, '5a5a5a5a-0006-4001-8006-000000000006',
  'long sleep resp');

-- Fixture 7: short_night_duration.
\set fixture_json `cat /fixtures/short_night_duration.json`
select pg_temp.seed_fixture(:'fixture_json'::jsonb,
  '5a5a5a5a-0007-4001-8007-000000000007');
select * from pg_temp.assert_expected(
  :'fixture_json'::jsonb, '5a5a5a5a-0007-4001-8007-000000000007',
  'short night');

select cmp_ok(
  abs((public.compute_daily_metrics(
    '5a5a5a5a-0007-4001-8007-000000000007', '2026-09-08'::date, 'Asia/Kolkata'
  )->'scores'->'sleep_breakdown'->>'duration_score')::numeric - 57.4),
  '<',
  0.15::numeric,
  'anchor 5: short 300-min night — duration ~57.4 vs the ~522 EWMA baseline');

-- Fixture 8: sleep_subs_partial.
\set fixture_json `cat /fixtures/sleep_subs_partial.json`
select pg_temp.seed_fixture(:'fixture_json'::jsonb,
  '5a5a5a5a-0008-4001-8008-000000000008');
select * from pg_temp.assert_expected(
  :'fixture_json'::jsonb, '5a5a5a5a-0008-4001-8008-000000000008',
  'sleep subs partial');

select is(
  (public.compute_daily_metrics(
    '5a5a5a5a-0008-4001-8008-000000000008', '2026-09-08'::date, 'Asia/Kolkata'
  )->'scores'->>'sleep_breakdown'),
  null,
  'anchor 6: incomplete sub-data — breakdown object absent for old clients');

-- Fixture 9: sleep_cold_floor_six_nights.
\set fixture_json `cat /fixtures/sleep_cold_floor_six_nights.json`
select pg_temp.seed_fixture(:'fixture_json'::jsonb,
  '5a5a5a5a-0009-4001-8009-000000000009');
select * from pg_temp.assert_expected(
  :'fixture_json'::jsonb, '5a5a5a5a-0009-4001-8009-000000000009',
  'six nights');

select is(
  (public.compute_daily_metrics(
    '5a5a5a5a-0009-4001-8009-000000000009', '2026-09-08'::date, 'Asia/Kolkata'
  )->'scores'->'sleep_breakdown'->>'duration_score')::numeric,
  85.6::numeric,
  'anchor 7: 6 nights — duration pinned to the 480 floor (411/480 = 85.6)');

-- Fixture 10: hrv_x3_scale_invariant.
\set fixture_json `cat /fixtures/hrv_x3_scale_invariant.json`
select pg_temp.seed_fixture(:'fixture_json'::jsonb,
  '5a5a5a5a-000a-4001-800a-00000000000a');
select * from pg_temp.assert_expected(
  :'fixture_json'::jsonb, '5a5a5a5a-000a-4001-800a-00000000000a',
  'hrv x3');

select is(
  (public.compute_daily_metrics(
    '5a5a5a5a-000a-4001-800a-00000000000a', '2026-09-08'::date, 'Asia/Kolkata'
  )->'scores'->'recovery_breakdown'->>'hrv_z')::numeric,
  (public.compute_daily_metrics(
    '5a5a5a5a-0003-4001-8003-000000000003', '2026-09-08'::date, 'Asia/Kolkata'
  )->'scores'->'recovery_breakdown'->>'hrv_z')::numeric,
  'anchor 8: x3-scaled history — identical ln-domain z to the base history');

-- Fixture 11: out_of_band_today.
\set fixture_json `cat /fixtures/out_of_band_today.json`
select pg_temp.seed_fixture(:'fixture_json'::jsonb,
  '5a5a5a5a-000b-4001-800b-00000000000b');
select * from pg_temp.assert_expected(
  :'fixture_json'::jsonb, '5a5a5a5a-000b-4001-800b-00000000000b',
  'out of band today');

-- Fixture 12: plausibility_rejections.
\set fixture_json `cat /fixtures/plausibility_rejections.json`
select pg_temp.seed_fixture(:'fixture_json'::jsonb,
  '5a5a5a5a-000c-4001-800c-00000000000c');
select * from pg_temp.assert_expected(
  :'fixture_json'::jsonb, '5a5a5a5a-000c-4001-800c-00000000000c',
  'plausibility rejections');

-- assert_expected's compute call already folded this user's baselines
-- (the rejection below reads the fold result).
select is(
  (select n_observations from public.user_baselines
   where user_id = '5a5a5a5a-000c-4001-800c-00000000000c'
     and metric_name = 'hrv_sdnn_ms'),
  6,
  'anchor 9: out-of-band history value rejected from the fold (6 of 7 counted)');

-- Fixture 13: acwr_monotony_windows.
\set fixture_json `cat /fixtures/acwr_monotony_windows.json`
select pg_temp.seed_fixture(:'fixture_json'::jsonb,
  '5a5a5a5a-000d-4001-800d-00000000000d');
select * from pg_temp.assert_expected(
  :'fixture_json'::jsonb, '5a5a5a5a-000d-4001-800d-00000000000d',
  'acwr monotony');

select is(
  (public.compute_daily_metrics(
    '5a5a5a5a-000d-4001-800d-00000000000d', '2026-09-08'::date, 'Asia/Kolkata'
  )->'scores'->>'acwr'),
  '1.95',
  'anchor 10: ACWR pinned 1.95 — zero-filled avg7 30.86 / avg28 15.86');

select is(
  (public.compute_daily_metrics(
    '5a5a5a5a-000d-4001-800d-00000000000d', '2026-09-08'::date, 'Asia/Kolkata'
  )->'scores'->>'training_monotony'),
  '2.27',
  'anchor 11: monotony pinned 2.27 — zero-filled acute week has variance');

-- Cross-fixture invariant: recovery in range wherever non-null.
select ok(
  (select recovery_score between 0 and 100
   from public.daily_computed_metrics
   where user_id = '5a5a5a5a-0005-4001-8005-000000000005'
     and local_date = '2026-09-08'::date),
  'anchor 12: full-data persisted recovery within 0..100');

select * from finish();
rollback;
